/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/logo.gltf src/components/Logo.jsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export function Logo3d(props) {
  const { nodes, materials } = useGLTF('/models/logo.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.alkimera.geometry} material={materials.Material} position={[0, 0.04, 0]} scale={2} />
    </group>
  )
}

useGLTF.preload('/models/logo.gltf')
